"""Unified modeling framework for LLM performance evaluation.

PyTorch-like interface for defining models with automatic sharding constraints.
"""

from .tensor import ShardedTensor, ShardedParameter
from .module import ShardedModule, ModuleInstance, WeightInstance, ActivationInstance

from llm_perf.kernels.op import (
    Op,
    MatmulOp,
    AttentionOp,
    LinearAttentionOp,
    RMSNormOp,
    EmbeddingOp,
    ActivationOp,
    MoEExpertOp,
    ViewOp,
    TransposeOp,
    CommOp,
    Conv2dOp,
    Conv3dOp,
    GroupNormOp,
)

from .base import (
    ShardedEmbedding,
    ShardedRMSNorm,
    ShardedAttention,
    ShardedFFN,
    ShardedLMHead,
    ShardedMoE,
    ShardedLinearAttention,
    ShardedConv2d,
    ShardedConv3d,
    ShardedGroupNorm,
    ShardedResNetBlock2d,
    ShardedResNetBlock3d,
    ShardedAttentionBlock2d,
    ShardedAttentionBlock3d,
    ShardedResNet,
    ShardedModulateDiT,
    ShardedPatchEmbed3D,
    ShardedTimestepEmbedder,
    ShardedMMDoubleStreamBlock,
    ShardedMMSingleStreamBlock,
    silu,
    gelu,
    relu,
    flash_attention,
    linear_attention,
)

from .mla import ShardedMLA

from .models import (
    ShardedTransformerBlock,
    ShardedMoEBlock,
    LlamaModel,
    DeepSeekModel,
    ShardedLayerNorm,
    ShardedT5Block,
    ShardedWanTextEncoder,
    ShardedWanDiTBlock,
    ShardedWanDiT,
    ShardedWanVAE,
    ShardedHYVideoDiT,
    Qwen3_5MoEModel,
    Qwen3_5Model,
    ShardedQwen3_5MoEBlock,
    ShardedQwen3_5DenseBlock,
    generate_layer_types,
    HunyuanImage3TextModel,
    HunyuanImage3DiffusionModel,
    ShardedHunyuanMoEBlock,
    ShardedHunyuanAttention,
)

from .encoder import (
    ShardedVAEEncoder,
    ShardedVAEDecoder,
    ShardedVAE,
    ShardedViTEncoder,
    ShardedViTBlock,
    ShardedPatchEmbedding,
    ShardedPositionalEmbedding,
    ShardedSpatialMerge,
    ShardedOutputProjection,
)

from llm_perf.strategy import (
    ParallelContext,
    SPType,
    CommDomain,
    PPStrategy,
    PPSchedule,
    PPModel,
    PPStageModule,
)

from .config_compat import SimpleModelConfig
from .registry import (
    ModelingRegistry,
    ModelInfo,
    register_all_models,
    get_model_presets,
    get_presets_by_sparse_type,
    get_presets_by_workload,
    get_presets_by_workload_grouped,
    create_model_from_config,
)

__all__ = [
    "ShardedTensor",
    "ShardedParameter",
    "ShardedModule",
    "ModuleInstance",
    "WeightInstance",
    "ActivationInstance",
    "Op",
    "MatmulOp",
    "AttentionOp",
    "LinearAttentionOp",
    "RMSNormOp",
    "EmbeddingOp",
    "ActivationOp",
    "MoEExpertOp",
    "ViewOp",
    "TransposeOp",
    "CommOp",
    "Conv2dOp",
    "Conv3dOp",
    "GroupNormOp",
    "ShardedEmbedding",
    "ShardedRMSNorm",
    "ShardedAttention",
    "ShardedFFN",
    "ShardedLMHead",
    "ShardedMoE",
    "ShardedLinearAttention",
    "ShardedTransformerBlock",
    "ShardedMoEBlock",
    "ShardedMLA",
    "silu",
    "gelu",
    "relu",
    "flash_attention",
    "linear_attention",
    "LlamaModel",
    "DeepSeekModel",
    "ShardedConv2d",
    "ShardedConv3d",
    "ShardedGroupNorm",
    "ShardedResNetBlock2d",
    "ShardedResNetBlock3d",
    "ShardedAttentionBlock2d",
    "ShardedAttentionBlock3d",
    "ShardedVAEEncoder",
    "ShardedVAEDecoder",
    "ShardedVAE",
    "ShardedResNet",
    "ShardedLayerNorm",
    "ShardedT5Block",
    "ShardedWanTextEncoder",
    "ShardedWanDiTBlock",
    "ShardedWanDiT",
    "ShardedWanVAE",
    "Qwen3_5MoEModel",
    "Qwen3_5Model",
    "ShardedQwen3_5MoEBlock",
    "ShardedQwen3_5DenseBlock",
    "generate_layer_types",
    "HunyuanImage3TextModel",
    "HunyuanImage3DiffusionModel",
    "ShardedHunyuanMoEBlock",
    "ShardedHunyuanAttention",
    "ShardedViTEncoder",
    "ShardedViTBlock",
    "ShardedPatchEmbedding",
    "ShardedPositionalEmbedding",
    "ShardedSpatialMerge",
    "ShardedOutputProjection",
    "ShardedHYVideoDiT",
    "ShardedModulateDiT",
    "ShardedPatchEmbed3D",
    "ShardedTimestepEmbedder",
    "ShardedMMDoubleStreamBlock",
    "ShardedMMSingleStreamBlock",
    "ParallelContext",
    "SPType",
    "CommDomain",
    "PPStrategy",
    "PPSchedule",
    "PPModel",
    "PPStageModule",
    "ModelingRegistry",
    "ModelInfo",
    "register_all_models",
    "get_model_presets",
    "get_presets_by_sparse_type",
    "get_presets_by_workload",
    "get_presets_by_workload_grouped",
    "create_model_from_config",
    "SimpleModelConfig",
]