"""HTML report generator."""

from typing import Dict, Any, Union
from pathlib import Path

from ..analyzer.training import TrainingResult
from ..analyzer.inference import InferenceResult


class HTMLReporter:
    """Generate HTML reports with interactive visualizations."""
    
    def __init__(self):
        self.template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 2.5em;
        }}
        .card {{
            background: white;
            border-radius: 10px;
            padding: 25px;
            margin-bottom: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .card h2 {{
            margin-top: 0;
            color: #333;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        .metrics-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }}
        .metric {{
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }}
        .metric-value {{
            font-size: 2em;
            font-weight: bold;
            display: block;
        }}
        .metric-label {{
            font-size: 0.9em;
            opacity: 0.9;
        }}
        .breakdown-table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}
        .breakdown-table th,
        .breakdown-table td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }}
        .breakdown-table th {{
            background: #667eea;
            color: white;
        }}
        .breakdown-table tr:hover {{
            background: #f5f5f5;
        }}
        .progress-bar {{
            background: #e0e0e0;
            border-radius: 10px;
            height: 20px;
            overflow: hidden;
        }}
        .progress-fill {{
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            height: 100%;
            border-radius: 10px;
            transition: width 0.3s ease;
        }}
        .config-section {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin: 10px 0;
        }}
        .config-section code {{
            background: #e9ecef;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p>LLM Performance Evaluation Report</p>
    </div>
    
    {content}
    
    <div class="card">
        <h2>📊 System Configuration</h2>
        <div class="config-section">
            <pre><code>{config_json}</code></pre>
        </div>
    </div>
    
    <footer style="text-align: center; padding: 20px; color: #666;">
        <p>Generated by LLM Performance Evaluator</p>
    </footer>
</body>
</html>
"""
    
    def report(
        self,
        result: Union[TrainingResult, InferenceResult],
        title: str = "Performance Report",
        config: Dict[str, Any] = None
    ) -> str:
        """Generate HTML report."""
        import json
        
        if isinstance(result, TrainingResult):
            content = self._training_content(result)
        else:
            content = self._inference_content(result)
        
        config_json = json.dumps(config or {}, indent=2)
        
        return self.template.format(
            title=title,
            content=content,
            config_json=config_json
        )
    
    def _training_content(self, result: TrainingResult) -> str:
        """Generate training report content."""
        return f"""
    <div class="card">
        <h2>🚀 Training Throughput</h2>
        <div class="metrics-grid">
            <div class="metric">
                <span class="metric-value">{result.samples_per_sec:.2f}</span>
                <span class="metric-label">Samples/sec</span>
            </div>
            <div class="metric">
                <span class="metric-value">{result.tokens_per_sec/1000:.1f}K</span>
                <span class="metric-label">Tokens/sec</span>
            </div>
            <div class="metric">
                <span class="metric-value">{result.time_per_step_sec*1000:.1f}</span>
                <span class="metric-label">ms/step</span>
            </div>
            <div class="metric">
                <span class="metric-value">{result.memory_per_gpu_gb:.1f}</span>
                <span class="metric-label">GB/GPU</span>
            </div>
        </div>
    </div>
    
    <div class="card">
        <h2>⏱️ Time Analysis</h2>
        <p><strong>Time per step:</strong> {result.time_per_step_sec*1000:.2f} ms</p>
        <p><strong>Time to solution:</strong> {result.time_to_solution_sec/3600:.2f} hours</p>
    </div>
    
    {self._breakdown_section(result.breakdown) if result.breakdown else ""}
"""
    
    def _inference_content(self, result: InferenceResult) -> str:
        """Generate inference report content."""
        return f"""
    <div class="card">
        <h2>⚡ Inference Performance</h2>
        <div class="metrics-grid">
            <div class="metric">
                <span class="metric-value">{result.prefill_time_sec*1000:.1f}</span>
                <span class="metric-label">TTFT (ms)</span>
            </div>
            <div class="metric">
                <span class="metric-value">{result.decode_time_per_step_sec*1000:.1f}</span>
                <span class="metric-label">TPOT (ms)</span>
            </div>
            <div class="metric">
                <span class="metric-value">{result.decode_tokens_per_sec:.1f}</span>
                <span class="metric-label">TPS</span>
            </div>
            <div class="metric">
                <span class="metric-value">{result.memory_per_gpu_gb:.1f}</span>
                <span class="metric-label">GB/GPU</span>
            </div>
        </div>
    </div>
    
    <div class="card">
        <h2>📈 Phase Breakdown</h2>
        <h3>Prefill Phase</h3>
        <p>Time to First Token (TTFT): {result.prefill_time_sec*1000:.2f} ms</p>
        <p>Throughput: {result.prefill_tokens_per_sec/1000:.1f}K tokens/sec</p>
        
        <h3>Decode Phase</h3>
        <p>Time Per Output Token (TPOT): {result.decode_time_per_step_sec*1000:.2f} ms</p>
        <p>Tokens Per Second (TPS): {result.decode_tokens_per_sec:.2f}</p>
        
        <h3>End-to-End</h3>
        <p>Total time: {result.total_time_sec:.2f} sec</p>
        <p>Total tokens: {result.total_tokens:,}</p>
        <p>Overall throughput: {result.total_tokens/result.total_time_sec if result.total_time_sec > 0 else 0:.2f} tokens/sec</p>
    </div>
    
    {self._breakdown_section(result.prefill_breakdown, "Prefill Breakdown") if result.prefill_breakdown else ""}
    {self._breakdown_section(result.decode_breakdown, "Decode Breakdown") if result.decode_breakdown else ""}
"""
    
    def _breakdown_section(self, breakdown, title: str = "Performance Breakdown") -> str:
        """Generate breakdown section."""
        data = breakdown.to_dict()
        
        time_info = data.get("time_breakdown", {})
        mem_info = data.get("memory_breakdown", {})
        
        return f"""
    <div class="card">
        <h2>🔍 {title}</h2>
        
        <h3>Time Distribution</h3>
        <table class="breakdown-table">
            <tr>
                <th>Category</th>
                <th>Time (ms)</th>
                <th>Percentage</th>
                <th>Visual</th>
            </tr>
            <tr>
                <td>Compute</td>
                <td>{time_info.get("compute_sec", 0)*1000:.2f}</td>
                <td>{time_info.get("compute_percent", 0):.1f}%</td>
                <td>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: {time_info.get("compute_percent", 0)}%"></div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Communication</td>
                <td>{time_info.get("communication_sec", 0)*1000:.2f}</td>
                <td>{time_info.get("communication_percent", 0):.1f}%</td>
                <td>
                    <div class="progress-bar">
                        <div class="progress-fill" style="width: {time_info.get("communication_percent", 0)}%"></div>
                    </div>
                </td>
            </tr>
        </table>
        
        <h3>Memory Usage</h3>
        <p>Peak Memory: {mem_info.get("peak_mb", 0)/1024:.2f} GB</p>
        <p>Activations: {mem_info.get("activation_mb", 0)/1024:.2f} GB</p>
        <p>Parameters: {mem_info.get("parameter_mb", 0)/1024:.2f} GB</p>
    </div>
"""
    
    def save(
        self,
        result: Union[TrainingResult, InferenceResult],
        path: Union[str, Path],
        title: str = "Performance Report",
        config: Dict[str, Any] = None
    ):
        """Save HTML report to file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write(self.report(result, title, config))
