"""HTML report generator."""

from typing import Dict, Any, Union
from pathlib import Path

from .base import BaseReporter
from llm_perf.analyzer import UnifiedResult


class HTMLReporter(BaseReporter):
    """Generate HTML reports with interactive visualizations."""

    def __init__(self):
        self.template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 2.5em;
        }}
        .card {{
            background: white;
            border-radius: 10px;
            padding: 25px;
            margin-bottom: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .card h2 {{
            margin-top: 0;
            color: #333;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        .metrics-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }}
        .metric {{
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }}
        .metric-value {{
            font-size: 2em;
            font-weight: bold;
            display: block;
        }}
        .metric-label {{
            font-size: 0.9em;
            opacity: 0.9;
        }}
        .phase-table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}
        .phase-table th,
        .phase-table td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }}
        .phase-table th {{
            background: #667eea;
            color: white;
        }}
        .phase-table tr:hover {{
            background: #f5f5f5;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p>Workload: {workload_name} ({workload_type})</p>
    </div>

    {content}

    <div class="card">
        <h2>Parameters</h2>
        <pre><code>{params_json}</code></pre>
    </div>

    <footer style="text-align: center; padding: 20px; color: #666;">
        <p>Generated by LLM Performance Evaluator</p>
    </footer>
</body>
</html>
"""

    def report(
        self,
        result: UnifiedResult,
        title: str = "Performance Report",
        generation_len: int = 0,
        **kwargs,
    ) -> str:
        """Generate HTML report."""
        import json

        content = self._generate_content(result, generation_len)
        params_json = json.dumps(result.params, indent=2)

        return self.template.format(
            title=title,
            workload_name=result.workload_name,
            workload_type=result.workload_type.value,
            content=content,
            params_json=params_json,
        )

    def _generate_content(self, result: UnifiedResult, generation_len: int = 0) -> str:
        """Generate report content."""
        html = f"""
    <div class="card">
        <h2>Performance Summary</h2>
        <div class="metrics-grid">
            <div class="metric">
                <span class="metric-value">{result.total_time_sec * 1000:.1f}</span>
                <span class="metric-label">Total Time (ms)</span>
            </div>
            <div class="metric">
                <span class="metric-value">{result.peak_memory_gb:.1f}</span>
                <span class="metric-label">Peak Memory (GB)</span>
            </div>
        </div>
    </div>
"""

        if result.throughput:
            html += """
    <div class="card">
        <h2>Throughput</h2>
        <div class="metrics-grid">
"""
            for metric_name, metric_value in result.throughput.items():
                if metric_name == "tokens_per_sec":
                    html += f"""
            <div class="metric">
                <span class="metric-value">{metric_value / 1000:.1f}K</span>
                <span class="metric-label">Tokens/sec</span>
            </div>
"""
                elif metric_name == "samples_per_sec":
                    html += f"""
            <div class="metric">
                <span class="metric-value">{metric_value:.2f}</span>
                <span class="metric-label">Samples/sec</span>
            </div>
"""
                elif metric_name == "pixels_per_sec":
                    html += f"""
            <div class="metric">
                <span class="metric-value">{metric_value / 1e6:.1f}M</span>
                <span class="metric-label">Pixels/sec</span>
            </div>
"""
            html += """
        </div>
    </div>
"""

        if result.phases:
            html += """
    <div class="card">
        <h2>Phase Breakdown</h2>
        <table class="phase-table">
            <tr>
                <th>Phase</th>
                <th>Component</th>
                <th>Single Time (ms)</th>
                <th>Repeats</th>
                <th>Total Time (ms)</th>
            </tr>
"""
            for phase in result.phases:
                html += f"""
            <tr>
                <td>{phase.name}</td>
                <td>{phase.component}</td>
                <td>{phase.single_time_sec * 1000:.2f}</td>
                <td>{phase.repeat_count}</td>
                <td>{phase.total_time_sec * 1000:.2f}</td>
            </tr>
"""
            html += """
        </table>
    </div>
"""

        return html

    def save(
        self,
        result: UnifiedResult,
        path: Union[str, Path],
        title: str = "Performance Report",
        generation_len: int = 0,
        **kwargs,
    ) -> None:
        """Save HTML report to file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, "w", encoding="utf-8") as f:
            f.write(self.report(result, title=title, generation_len=generation_len, **kwargs))
